### ISSUE TITLE
MTA Java react client doesn't pull movies

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/docker-fifth-birthday#31]
Are we missing an environment variable or something?

![screen shot 2018-03-23 at 2 27 29 pm](https://user-images.githubusercontent.com/113855/37854045-7daff9c4-2ea6-11e8-9d63-3fd3df588c08.png)

**Comment by spara** [comment]
I think they either didn't run add_ee_pwd_host.sh or it was run on a worker that didn't return the hostname of ee PWD instance. To make sure that this happens I could have them edit the Dockerfile directly to as the hostname directly.

**Comment by fernandrone** [comment]
It seems to be an issue with add_ee_pwd_host @spara 

I had the same problem, and I had run the add_ee_pwd_host.sh script... However, the script actually _adds_ the hostname before whatever value was already there (instead of replacing it). I.e. after running it I got:

```
cat react-client/Dockerfile
FROM node:latest AS build
ENV API_HOST=ip172-18-0-13-(...).direct.beta-hybrid.play-with-docker.com:30080
ENV API_HOST=ip172-18-0-7-(...).direct.beta-hybrid.play-with-docker.com:30080
WORKDIR /usr/src/react-client
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/react-client/src/static /usr/share/nginx/html
```

Where ip172-18-0-13-(...).direct.beta-hybrid.play-with-docker.com was the correct hostname, and ip172-18-0-7-(...).direct.beta-hybrid.play-with-docker.com was already present on the Dockerfile when I started the lab.

_Furthermore_, the add_ee_pwd_host script hardcodes the port as 30080 (unlike the description of the Dockerfile given in the tutorial, which shows no port). However, when I deployed on UCP,  it assigned nodePort: 30543 to the movieplex7 load balancer.

I'm don't have a lot of experience with Kubernetes and this is my first time using Docker UCP, but it would not let me change the nodePort value on the load balancer spec. So I had to manually edit the react-client Dockerfile and publish a new image:

```
cat react-client/Dockerfile
FROM node:latest AS build
ENV API_HOST=ip172-18-0-13-(...).direct.beta-hybrid.play-with-docker.com:30543
WORKDIR /usr/src/react-client
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/react-client/src/static /usr/share/nginx/html
```

After that, it worked :)

Is there any way to set the nodePort value on Movieplex load balancer? So we could set it 30800 as well.

**Comment by fernandrone** [comment]
Apparently, if I set nodePort during resource creation, it works!

**Comment by fernandrone** [comment]
So we'd need something like this: https://github.com/dockersamples/docker-fifth-birthday/pull/33

Also it'd probably be better to edit the add_ee_pwd_host script so it _replaces_ the API Host var, instead of adding a new one. However I'm really in a hurry because I've got a Docker Workshop to mentor :smile: (and so I might have missed somehting, reviews are appreciated!)

Cheers

**Comment by spara** [comment]
Please see the note in [#33](https://github.com/dockersamples/docker-fifth-birthday/pull/33). I've added a script that sets the API_HOST env for just a kubernetes deploy - also change the port in the script to 30088 which is defined in the service manifest.
